# Generated by Django 5.2.6 on 2025-09-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("mvp", "MVP"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("series_c", "Series C"),
                            ("growth", "Growth"),
                            ("ipo", "IPO"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Comma-separated tags"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
