# Generated by Django 5.2.6 on 2025-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="tags",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="startup",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
