# Generated by Django 5.2.6 on 2025-09-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
