# Generated by Django 5.2.6 on 2025-09-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_note_updated_at_remove_note_user"),
    ]

    operations = []
