# Generated by Django 5.2.6 on 2025-09-22 22:34

from django.db import migrations


def assign_notes_to_admin(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    User = apps.get_model('auth', 'User')
    
    admin_user = User.objects.filter(username='admin').first()
    if admin_user:
        Note.objects.filter(user__isnull=True).update(user=admin_user)


def reverse_assign_notes_to_admin(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    Note.objects.filter(user__username='admin').update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_user_alter_note_unique_together"),
    ]

    operations = [
        migrations.RunPython(assign_notes_to_admin, reverse_assign_notes_to_admin),
    ]
