# Generated by Django 5.2.6 on 2025-09-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlistitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="user",
        ),
    ]
